export const DISPATCH_ERROR = "DISPATCH_ERROR";
export const CLEAR_ERROR_STATE = "CLEAR_ERROR_STATE";

export const POST_REFERRAL_SUCCESS = "POST_REFERRAL_SUCCESS";
export const POST_REFERRAL_FAIL = "POST_REFERRAL_FAIL";
export const POST_REFERRAL_REQUEST = "POST_REFERRAL_REQUEST";
export const POST_REFERRAL_LOADING = "POST_REFERRAL_LOADING";
